//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainRes
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDetail
    {
        public decimal AdminID { get; set; }
        public string AdminName { get; set; }
        public string Admin_Password { get; set; }
    }
}
