//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainRes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking_Details()
        {
            this.CancelTickets = new HashSet<CancelTicket>();
        }
    
        public decimal PNR_NO { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public Nullable<decimal> TrainNo { get; set; }
        public string Class_Type { get; set; }
        public Nullable<float> Total_Price { get; set; }
        public int NumberofTickets { get; set; }
        public Nullable<System.DateTime> Booking_Date_Time { get; set; }
        public string Booking_Status { get; set; }
    
        public virtual TrainDetail TrainDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelTicket> CancelTickets { get; set; }
    }
}
