//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainRes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelTicket
    {
        public decimal Cancel_ID { get; set; }
        public Nullable<decimal> PNR_No { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<decimal> TrainNo { get; set; }
        public Nullable<int> Refund_Amount { get; set; }
        public Nullable<System.DateTime> Cancel_Date_Time { get; set; }
    
        public virtual Booking_Details Booking_Details { get; set; }
        public virtual TrainDetail TrainDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
