//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainRes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPrice
    {
        public int S_No { get; set; }
        public Nullable<decimal> TrainNo { get; set; }
        public Nullable<int> C1_AC_Price { get; set; }
        public Nullable<int> C2_AC_Price { get; set; }
        public Nullable<int> SL_Price { get; set; }
    
        public virtual TrainDetail TrainDetail { get; set; }
    }
}
