//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainRes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainDetail()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
            this.CancelTickets = new HashSet<CancelTicket>();
            this.Class_Type = new HashSet<Class_Type>();
            this.TicketPrices = new HashSet<TicketPrice>();
        }
    
        public decimal TrainNo { get; set; }
        public string TrainName { get; set; }
        public string Source_Station { get; set; }
        public string Final_Station { get; set; }
        public string TrainStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelTicket> CancelTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_Type> Class_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketPrice> TicketPrices { get; set; }
    }
}
